# src/fatfloppy/core/format_definitions.py
"""
Predefined format profiles for various common floppy disk types.

This module contains the `FLOPPY_FORMATS` dictionary, which serves as a
database of known floppy disk formats. Each entry is a `FormatProfile`
object that encapsulates the physical geometry (cylinders, heads, sectors, etc.)
and the logical filesystem configuration (e.g., FAT12 BPB or CP/M DPB) for a
specific format.

These profiles are used by the `DiskController` for auto-detection,
formatting, and creating new disk images.

TODO:
    - Adjust gap3_bytes based on doc: https://www.isdaman.com/alsos/hardware/fdc/floppy.htm
    - Verify against https://retrocmp.de/fdd/general/floppy-formats.htm
"""
from typing import Dict

from .physical_format import PhysicalFormat, TrackFormat
from .format_profile import FormatProfile
from .filesystems.fat12fs import FATVolumeInfo
from .filesystems.cpm_fs import CPMDiskParameterBlock
from .filesystems.hdos_fs import HDOSLabelRecord

FLOPPY_FORMATS: Dict[str, FormatProfile] = {
    "ibm_5.25_160k": FormatProfile(
        name="ibm_5.25_160k",
        description="5.25\" DD 160KB (40 tracks, 1 head, 8 sectors)",
        physical_format=PhysicalFormat(
            cylinders=40,
            heads=1,
            rpm=300,
            heads_inverted=False,
            bytes_per_sector=512,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=39,
                    head_start=0,
                    head_end=0,
                    sectors_per_track=8,
                    encoding="MFM",
                    rate=250,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=84,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=8,
            bytes_per_sector=512,
            num_heads=1,
            total_sectors=320,
            media_descriptor=0xFE,
            root_entries=64,
            sectors_per_fat=1,
            sectors_per_cluster=1,
        ),
    ),
    "ibm_5.25_180k": FormatProfile(
        name="ibm_5.25_180k",
        description="5.25\" DD 180KB (40 tracks, 1 head, 9 sectors)",
        physical_format=PhysicalFormat(
            cylinders=40,
            heads=1,
            rpm=300,
            heads_inverted=False,
            bytes_per_sector=512,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=39,
                    head_start=0,
                    head_end=0,
                    sectors_per_track=9,
                    encoding="MFM",
                    rate=250,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=84,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=9,
            bytes_per_sector=512,
            num_heads=1,
            total_sectors=360,
            media_descriptor=0xFC,
            root_entries=64,
            sectors_per_fat=2,
            sectors_per_cluster=1,
        ),
    ),
    "ibm_5.25_320k": FormatProfile(
        name="ibm_5.25_320k",
        description="5.25\" DD 320KB (40 tracks, 2 heads, 8 sectors)",
        physical_format=PhysicalFormat(
            cylinders=40,
            heads=2,
            rpm=300,
            heads_inverted=False,
            bytes_per_sector=512,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=39,
                    head_start=0,
                    head_end=1,
                    sectors_per_track=8,
                    encoding="MFM",
                    rate=250,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=84,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=8,
            bytes_per_sector=512,
            num_heads=2,
            total_sectors=640,
            media_descriptor=0xFF,
            root_entries=112,
            sectors_per_fat=1,
            sectors_per_cluster=2,
        ),
    ),
    "ibm_5.25_360k": FormatProfile(
        name="ibm_5.25_360k",
        description="5.25\" DD 360KB (40 tracks, 2 heads, 9 sectors)",
        physical_format=PhysicalFormat(
            cylinders=40,
            heads=2,
            rpm=300,
            heads_inverted=False,
            bytes_per_sector=512,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=39,
                    head_start=0,
                    head_end=1,
                    sectors_per_track=9,
                    encoding="MFM",
                    rate=250,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=84,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=9,
            bytes_per_sector=512,
            num_heads=2,
            total_sectors=720,
            media_descriptor=0xFD,
            root_entries=112,
            sectors_per_fat=2,
            sectors_per_cluster=2,
        ),
    ),
    "ibm_5.25_1.2m": FormatProfile(
        name="ibm_5.25_1.2m",
        description="5.25\" HD 1.2MB (80 tracks, 2 heads, 15 sectors)",
        physical_format=PhysicalFormat(
            cylinders=80,
            heads=2,
            rpm=360,
            heads_inverted=False,
            bytes_per_sector=512,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=79,
                    head_start=0,
                    head_end=1,
                    sectors_per_track=15,
                    encoding="MFM",
                    rate=500,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=84,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=15,
            bytes_per_sector=512,
            num_heads=2,
            total_sectors=2400,
            media_descriptor=0xF9,
            root_entries=224,
            sectors_per_fat=7,
            sectors_per_cluster=1,
        ),
    ),
    "ibm_3.5_320k": FormatProfile(
        name="ibm_3.5_320k",
        description="3.5\" DD 320KB (80 tracks, 1 head, 8 sectors)",
        physical_format=PhysicalFormat(
            cylinders=80,
            heads=1,
            rpm=300,
            heads_inverted=False,
            bytes_per_sector=512,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=79,
                    head_start=0,
                    head_end=0,
                    sectors_per_track=8,
                    encoding="MFM",
                    rate=250,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=84,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=8,
            bytes_per_sector=512,
            num_heads=1,
            total_sectors=640,
            media_descriptor=0xFF,
            root_entries=112,
            sectors_per_fat=1,
            sectors_per_cluster=2,
        ),
    ),
    "ibm_3.5_360k": FormatProfile(
        name="ibm_3.5_360k",
        description="3.5\" DD 360KB (80 tracks, 1 head, 9 sectors)",
        physical_format=PhysicalFormat(
            cylinders=80,
            heads=1,
            rpm=300,
            heads_inverted=False,
            bytes_per_sector=512,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=79,
                    head_start=0,
                    head_end=0,
                    sectors_per_track=9,
                    encoding="MFM",
                    rate=250,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=84,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=9,
            bytes_per_sector=512,
            num_heads=1,
            total_sectors=720,
            media_descriptor=0xFC,
            root_entries=112,
            sectors_per_fat=2,
            sectors_per_cluster=2,
        ),
    ),
    "ibm_3.5_640k": FormatProfile(
        name="ibm_3.5_640k",
        description="3.5\" DD 640KB (80 tracks, 2 heads, 8 sectors)",
        physical_format=PhysicalFormat(
            cylinders=80,
            heads=2,
            rpm=300,
            heads_inverted=False,
            bytes_per_sector=512,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=79,
                    head_start=0,
                    head_end=1,
                    sectors_per_track=8,
                    encoding="MFM",
                    rate=250,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=84,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=8,
            bytes_per_sector=512,
            num_heads=2,
            total_sectors=1280,
            media_descriptor=0xFF,
            root_entries=112,
            sectors_per_fat=2,
            sectors_per_cluster=2,
        ),
    ),
    "ibm_3.5_720k": FormatProfile(
        name="ibm_3.5_720k",
        description="3.5\" DD 720KB (80 tracks, 2 heads, 9 sectors)",
        physical_format=PhysicalFormat(
            cylinders=80,
            heads=2,
            rpm=300,
            heads_inverted=False,
            bytes_per_sector=512,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=79,
                    head_start=0,
                    head_end=1,
                    sectors_per_track=9,
                    encoding="MFM",
                    rate=250,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=84,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=9,
            bytes_per_sector=512,
            num_heads=2,
            total_sectors=1440,
            media_descriptor=0xF9,
            root_entries=112,
            sectors_per_fat=3,
            sectors_per_cluster=2,
        ),
    ),
    "ibm_3.5_800k": FormatProfile(
        name="ibm_3.5_800k",
        description="3.5\" DD 800KB (80 tracks, 2 heads, 10 sectors)",
        physical_format=PhysicalFormat(
            cylinders=80,
            heads=2,
            rpm=300,
            heads_inverted=False,
            bytes_per_sector=512,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=79,
                    head_start=0,
                    head_end=1,
                    sectors_per_track=10,
                    encoding="MFM",
                    rate=250,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=30,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=10,
            bytes_per_sector=512,
            num_heads=2,
            total_sectors=1600,
            media_descriptor=0xF9,
            root_entries=112,
            sectors_per_fat=3,
            sectors_per_cluster=2,
        ),
    ),
    "ibm_3.5_1.44m": FormatProfile(
        name="ibm_3.5_1.44m",
        description="3.5\" HD 1.44MB (80 tracks, 2 heads, 18 sectors)",
        physical_format=PhysicalFormat(
            cylinders=80,
            heads=2,
            rpm=300,
            heads_inverted=False,
            bytes_per_sector=512,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=79,
                    head_start=0,
                    head_end=1,
                    sectors_per_track=18,
                    encoding="MFM",
                    rate=500,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=84,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=18,
            bytes_per_sector=512,
            num_heads=2,
            total_sectors=2880,
            media_descriptor=0xF0,
            root_entries=224,
            sectors_per_fat=9,
            sectors_per_cluster=1,
        ),
    ),
    "ibm_3.5_2.88m": FormatProfile(
        name="ibm_3.5_2.88m",
        description="3.5\" ED 2.88MB (80 tracks, 2 heads, 36 sectors)",
        physical_format=PhysicalFormat(
            cylinders=80,
            heads=2,
            rpm=300,
            heads_inverted=False,
            bytes_per_sector=512,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=79,
                    head_start=0,
                    head_end=1,
                    sectors_per_track=36,
                    encoding="MFM",
                    rate=1000,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=41,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=36,
            bytes_per_sector=512,
            num_heads=2,
            total_sectors=5760,
            reserved_sectors=2,
            media_descriptor=0xF0,
            root_entries=224,
            sectors_per_fat=9,
            sectors_per_cluster=2,
        ),
    ),
    "ibm_3.5_1.68m": FormatProfile(
        name="ibm_3.5_1.68m",
        description="3.5\" HD 1.68MB (80 tracks, 2 heads, 21 sectors)",
        physical_format=PhysicalFormat(
            cylinders=80,
            heads=2,
            rpm=300,
            heads_inverted=False,
            bytes_per_sector=512,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=79,
                    head_start=0,
                    head_end=1,
                    sectors_per_track=21,
                    encoding="MFM",
                    rate=500,
                    interleave=2,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=12,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=21,
            bytes_per_sector=512,
            num_heads=2,
            total_sectors=3360,
            media_descriptor=0xF0,
            root_entries=16,
            sectors_per_fat=5,
            sectors_per_cluster=2,
        ),
    ),
    "ibm_3.5_1.72m": FormatProfile(
        name="ibm_3.5_1.72m",
        description="3.5\" HD 1.72MB (82 tracks, 2 heads, 21 sectors)",
        physical_format=PhysicalFormat(
            cylinders=82,
            heads=2,
            rpm=300,
            heads_inverted=False,
            bytes_per_sector=512,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=81,
                    head_start=0,
                    head_end=1,
                    sectors_per_track=21,
                    encoding="MFM",
                    rate=500,
                    interleave=2,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=12,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=21,
            bytes_per_sector=512,
            num_heads=2,
            total_sectors=3444,
            media_descriptor=0xF0,
            root_entries=16,
            sectors_per_fat=6,
            sectors_per_cluster=2,
        ),
    ),
    "ibm_8_250k": FormatProfile(
        name="ibm_8_250k",
        description="8\" SD 250KB (77 tracks, 1 head, 26 sectors)",
        physical_format=PhysicalFormat(
            cylinders=77,
            heads=1,
            rpm=360,
            heads_inverted=False,
            bytes_per_sector=128,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=76,
                    head_start=0,
                    head_end=0,
                    sectors_per_track=26,
                    encoding="FM",
                    rate=250,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=26,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=26,
            bytes_per_sector=128,
            num_heads=1,
            total_sectors=2002,
            media_descriptor=0xFE,
            root_entries=68,
            sectors_per_fat=6,
            sectors_per_cluster=4,
        ),
    ),
    "ibm_8_298k": FormatProfile(
        name="ibm_8_298k",
        description="8\" SD 298KB (77 tracks, 1 head, 15 sectors)",
        physical_format=PhysicalFormat(
            cylinders=77,
            heads=1,
            rpm=360,
            heads_inverted=False,
            bytes_per_sector=256,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=76,
                    head_start=0,
                    head_end=0,
                    sectors_per_track=15,
                    encoding="FM",
                    rate=250,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=26,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=15,
            bytes_per_sector=256,
            num_heads=1,
            total_sectors=1155,
            media_descriptor=0xFE,
            root_entries=56,
            sectors_per_fat=4,
            sectors_per_cluster=2,
        ),
    ),
    "ibm_8_315k": FormatProfile(
        name="ibm_8_315k",
        description="8\" SD 315KB (77 tracks, 1 head, 8 sectors)",
        physical_format=PhysicalFormat(
            cylinders=77,
            heads=1,
            rpm=360,
            heads_inverted=False,
            bytes_per_sector=512,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=76,
                    head_start=0,
                    head_end=0,
                    sectors_per_track=8,
                    encoding="FM",
                    rate=250,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=26,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=8,
            bytes_per_sector=512,
            num_heads=1,
            total_sectors=616,
            media_descriptor=0xFE,
            root_entries=64,
            sectors_per_fat=2,
            sectors_per_cluster=1,
        ),
    ),
    "ibm_8_500k": FormatProfile(
        name="ibm_8_500k",
        description="8\" SD 500KB (77 tracks, 2 heads, 26 sectors)",
        physical_format=PhysicalFormat(
            cylinders=77,
            heads=2,
            rpm=360,
            heads_inverted=False,
            bytes_per_sector=128,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=76,
                    head_start=0,
                    head_end=1,
                    sectors_per_track=26,
                    encoding="FM",
                    rate=250,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=26,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=26,
            bytes_per_sector=128,
            num_heads=2,
            total_sectors=4004,
            reserved_sectors=2,
            media_descriptor=0xFD,
            root_entries=96,
            sectors_per_fat=12,
            sectors_per_cluster=4,
        ),
    ),
    "ibm_8_590k": FormatProfile(
        name="ibm_8_590k",
        description="8\" SD 590KB (77 tracks, 2 heads, 15 sectors)",
        physical_format=PhysicalFormat(
            cylinders=77,
            heads=2,
            rpm=360,
            heads_inverted=False,
            bytes_per_sector=256,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=76,
                    head_start=0,
                    head_end=1,
                    sectors_per_track=15,
                    encoding="FM",
                    rate=250,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=26,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=15,
            bytes_per_sector=256,
            num_heads=2,
            total_sectors=2310,
            reserved_sectors=2,
            media_descriptor=0xFD,
            root_entries=96,
            sectors_per_fat=7,
            sectors_per_cluster=2,
        ),
    ),
    "ibm_8_630k": FormatProfile(
        name="ibm_8_630k",
        description="8\" DD 630KB (77 tracks, 1 head, 8 sectors)",
        physical_format=PhysicalFormat(
            cylinders=77,
            heads=1,
            rpm=360,
            heads_inverted=False,
            bytes_per_sector=1024,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=76,
                    head_start=0,
                    head_end=0,
                    sectors_per_track=8,
                    encoding="MFM",
                    rate=500,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=54,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=8,
            bytes_per_sector=1024,
            num_heads=1,
            total_sectors=616,
            media_descriptor=0x00,
            root_entries=96,
            sectors_per_fat=1,
            sectors_per_cluster=1,
        ),
    ),
    "ibm_8_1025k": FormatProfile(
        name="ibm_8_1025k",
        description="8\" DD 1MB (77 tracks, 2 heads, 26 sectors)",
        physical_format=PhysicalFormat(
            cylinders=77,
            heads=2,
            rpm=360,
            heads_inverted=False,
            bytes_per_sector=256,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=76,
                    head_start=0,
                    head_end=1,
                    sectors_per_track=26,
                    encoding="MFM",
                    rate=500,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=54,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=26,
            bytes_per_sector=256,
            num_heads=2,
            total_sectors=4004,
            media_descriptor=0xFE,
            root_entries=192,
            sectors_per_fat=6,
            sectors_per_cluster=4,
        ),
    ),
    "ibm_8_1180k": FormatProfile(
        name="ibm_8_1180k",
        description="8\" DD 1.2MB (77 tracks, 2 heads, 15 sectors)",
        physical_format=PhysicalFormat(
            cylinders=77,
            heads=2,
            rpm=360,
            heads_inverted=False,
            bytes_per_sector=512,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=76,
                    head_start=0,
                    head_end=1,
                    sectors_per_track=15,
                    encoding="MFM",
                    rate=500,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=54,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=15,
            bytes_per_sector=512,
            num_heads=2,
            total_sectors=2310,
            reserved_sectors=2,
            media_descriptor=0xFE,
            root_entries=192,
            sectors_per_fat=4,
            sectors_per_cluster=2,
        ),
    ),
    "ibm_8_1260k": FormatProfile(
        name="ibm_8_1260k",
        description="8\" DD 1.25MB (77 tracks, 2 heads, 8 sectors)",
        physical_format=PhysicalFormat(
            cylinders=77,
            heads=2,
            rpm=360,
            heads_inverted=False,
            bytes_per_sector=1024,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=76,
                    head_start=0,
                    head_end=1,
                    sectors_per_track=8,
                    encoding="MFM",
                    rate=500,
                    interleave=1,
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=54,
                ),
            ],
        ),
        filesystem_type="FAT12",
        filesystem_config=FATVolumeInfo(
            sectors_per_track=8,
            bytes_per_sector=1024,
            num_heads=2,
            total_sectors=1232,
            media_descriptor=0xFE,
            root_entries=192,
            sectors_per_fat=2,
            sectors_per_cluster=1,
        ),
    ),
    # Standard IBM 3740 compatible format
    "cpm_8_sssd_250k": FormatProfile(
        name="cpm_8_sssd_250k",
        description="8\" SSSD 250KB CP/M (77 tracks, 1 head, 26 sectors/track, 128 bytes/sector, 1K blocks)",
        physical_format=PhysicalFormat(
            cylinders=77,  # Usually 0-76
            heads=1,
            rpm=360,
            heads_inverted=False,
            bytes_per_sector=128,  # Physical sector size matches CP/M logical sector size
            image_in_sector_id_order=True,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=76,
                    head_start=0,
                    head_end=0,
                    sectors_per_track=26,  # Physical sectors per track
                    encoding="FM",  # Single Density typically FM
                    rate=250,  # Common for 8" SD
                    interleave=6,  # Common for IBM 3740 SSSD
                    id_start=1,
                    iam_present=True,
                    gap3_bytes=26,  # Typical value
                ),
            ],
        ),
        filesystem_type="CPM",
        filesystem_config=CPMDiskParameterBlock(
            spt=26,   # Number of 128-byte logical sectors per track
            bsh=3,    # Block shift: 2^3 = 8 => 8 * 128 = 1024 byte blocks (1K)
            blm=7,    # Block mask: 2^BSH - 1 = 7
            exm=0,    # Extent mask: 0 for 16KB extents (1K blocks * 16 = 16KB)
            dsm=242,  # Max alloc block num: (250KB total - 2 tracks sys - ~6KB dir) / 1KB blocks approx.
            drm=63,   # Directory entries max: 64 entries - 1 = 63
            al0=0xC0,  # Allocation bitmap for directory blocks (first 2 blocks for dir: 11000000)
            al1=0x00,
            cks=0,    # Checksum vector size: 0 (no checksumming for directory)
            off=2,    # Offset: 2 reserved tracks for system (tracks 0 and 1)
        ),
    ),
    "cpm_8_ssdd_imsai_mixed": FormatProfile(
        name="cpm_8_ssdd_imsai_mixed",
        description="8\" SSDD IMSAI Mixed Density (T0 FM, T1-76 MFM, ~500KB)",
        physical_format=PhysicalFormat(
            cylinders=77,
            heads=1,
            rpm=360,
            heads_inverted=False,
            bytes_per_sector=128,
            image_in_sector_id_order=True,
            track_formats=[
                TrackFormat(
                    track_start=0,
                    track_end=0,
                    head_start=0,
                    head_end=0,
                    sectors_per_track=26,
                    bytes_per_sector=128,
                    encoding="FM",
                    rate=250,
                    interleave=6,
                ),
                TrackFormat(
                    track_start=1,
                    track_end=76,
                    head_start=0,
                    head_end=0,
                    sectors_per_track=26,
                    bytes_per_sector=256,
                    encoding="MFM",
                    rate=500,
                    interleave=9,
                ),
            ],
        ),
        filesystem_type="CPM",
        filesystem_config=CPMDiskParameterBlock(
            spt=52,
            bsh=4,
            blm=15,
            exm=0,
            dsm=242,
            drm=63,
            al0=0xC0,
            al1=0x00,
            cks=0,
            off=2,
        ),
    ),
    # --- HDOS 2.0 / 3.0 Formats ---
    # NOTE: HDOS 2.0+ INIT places the DIR and GRT at lower LBAs than HDOS 1.x.
    # We use representative values from real disks as defaults for formatting.
    "hdos_5.25_100k": FormatProfile(
        name="hdos_5.25_100k",
        description="5.25\" SSSD 100KB HDOS 2.0 (40 tracks, 1 head, 10 sectors/track)",
        physical_format=PhysicalFormat(
            cylinders=40,
            heads=1,
            rpm=300,
            heads_inverted=False,
            bytes_per_sector=256,
            track_formats=[
                TrackFormat(0, 39, 0, 0, 10, "FM", 250, 1, id_start=1)
            ],
        ),
        filesystem_type="HDOS",
        filesystem_config=HDOSLabelRecord(
            title="HDOS 2.0 DISK",
            volume_number=0,
            cluster_factor=2,
            dir_start_block=130, # Representative value for HDOS 2.0+
            grt_start_block=148  # Representative value for HDOS 2.0+
        ),
    ),

    # H17/H37 2-Side, 40-track, Single Density (400 sectors -> 200 groups * 2 SPG)
    "hdos_5.25_200k_dssd": FormatProfile(
        name="hdos_5.25_200k_dssd",
        description="5.25\" DSSD 200KB HDOS 3.0 (40 tracks, 2 heads, 10 sectors/track, FM)",
        physical_format=PhysicalFormat(
            cylinders=40,
            heads=2,
            rpm=300,
            heads_inverted=False,
            bytes_per_sector=256,
            track_formats=[
                TrackFormat(0, 39, 0, 1, 10, "FM", 250, 1, id_start=1)
            ],
        ),
        filesystem_type="HDOS",
        filesystem_config=HDOSLabelRecord(
            title="HDOS 3.0 DISK",
            volume_number=0,
            cluster_factor=4,
            dir_start_block=130,
            grt_start_block=148
        ),
    ),

    # H37 1-Side, 80-track, Double Density (640 sectors -> 160 groups * 4 SPG)
    "hdos_5.25_320k_ssdd": FormatProfile(
        name="hdos_5.25_320k_ssdd",
        description="5.25\" SSDD 320KB HDOS 3.0 (80 tracks, 1 head, 16 sectors/track, MFM)",
        physical_format=PhysicalFormat(
            cylinders=80,
            heads=1,
            rpm=300,
            heads_inverted=False,
            bytes_per_sector=256,
            track_formats=[
                TrackFormat(0, 79, 0, 0, 16, "MFM", 250, 1, id_start=1)
            ],
        ),
        filesystem_type="HDOS",
        filesystem_config=HDOSLabelRecord(
            title="HDOS 3.0 DISK",
            volume_number=0,
            cluster_factor=4,
            dir_start_block=130,
            grt_start_block=148
        ),
    ),

    # H47 2-Side, 77-track, Double Density (4000 sectors -> 250 groups * 16 SPG)
    "hdos_8_1m_dsdd": FormatProfile(
        name="hdos_8_1m_dsdd",
        description="8\" DSDD 1MB HDOS 3.0 (77 tracks, 2 heads, 26 sectors/track, MFM)",
        physical_format=PhysicalFormat(
            cylinders=77,
            heads=2,
            rpm=360,
            heads_inverted=False,
            bytes_per_sector=256,
            track_formats=[
                TrackFormat(0, 76, 0, 1, 26, "MFM", 500, 1, id_start=1)
            ],
        ),
        filesystem_type="HDOS",
        filesystem_config=HDOSLabelRecord(
            title="HDOS 3.0 DISK",
            volume_number=0,
            cluster_factor=16,
            dir_start_block=130,
            grt_start_block=148
        ),
    ),
}
